[package]
name = "marvell-88mc200"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
vcell = "0.1.3"

[dependencies.cortex-m-rt]
optional = true
version = ">=0.6.15,<0.8"

[features]
default = ["rt"]
rt = ["cortex-m-rt/device"]
